version: '3'

services:

  db:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./seed:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  mysql_volume: